name: openmmenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cudatoolkit=11.8.0
  - decorator=5.1.1
  - executing=0.8.3
  - fftw=3.3.10
  - ipython=8.4.0
  - jedi=0.18.1
  - ld_impl_linux-64=2.39
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsqlite=3.39.4
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - numpy=1.23.4
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - openmm=7.7.0
  - openssl=3.0.7
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.10.6
  - python_abi=3.10
  - readline=8.1.2
  - setuptools=65.5.0
  - six=1.16.0
  - stack_data=0.2.0
  - tk=8.6.12
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.54.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - packaging==24.1
      - pandas==2.2.3
      - pillow==10.4.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - tqdm==4.66.5
      - tzdata==2024.2
prefix: /storage/homefs/sl22n046/.conda/envs/openmmenv
